# Generated by Django 3.0.8 on 2020-07-22 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_builder', '0003_auto_20200721_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='id',
        ),
        migrations.AddField(
            model_name='course',
            name='subject_ptr',
            field=models.OneToOneField(auto_created=True, default=5, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schedule_builder.Subject'),
            preserve_default=False,
        ),
    ]
