# Generated by Django 3.0.8 on 2020-07-22 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_builder', '0005_delete_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=0, verbose_name='Course Code')),
                ('type', models.CharField(max_length=10, verbose_name='Lecture/Dis/Lab/Sem')),
                ('section', models.CharField(max_length=4)),
                ('units', models.IntegerField(default=0)),
                ('instructor', models.CharField(default='TBA', max_length=30)),
                ('time', models.CharField(default='TBA', max_length=20)),
                ('place', models.CharField(default='TBA', max_length=15)),
                ('final', models.CharField(default='TBA', max_length=30)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='schedule_builder.Subject')),
            ],
        ),
    ]
