# Generated by Django 3.0.8 on 2020-07-22 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_builder', '0006_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Name', max_length=25)),
            ],
        ),
        migrations.RenameModel(
            old_name='Schedule',
            new_name='ClassSchedule',
        ),
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(default='default course', max_length=30),
        ),
        migrations.CreateModel(
            name='ProjectedEnrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_term', models.CharField(default='Fall 2020', max_length=15)),
                ('course_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projected_enrollments', to='schedule_builder.CoursePlan')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projected_enrollments', to='schedule_builder.Subject')),
            ],
        ),
        migrations.AddField(
            model_name='courseplan',
            name='courses',
            field=models.ManyToManyField(related_name='course_plans', through='schedule_builder.ProjectedEnrollment', to='schedule_builder.Subject'),
        ),
    ]
