# Generated by Django 3.0.8 on 2020-08-23 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_builder', '0010_enrollment_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='name',
            field=models.CharField(default='Default Name', max_length=25),
        ),
    ]
