# Generated by Django 3.0.8 on 2020-08-23 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_builder', '0011_schedule_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='academic_term',
            field=models.CharField(default='Fall 2020', max_length=15),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='schedule_builder.Course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrollment',
            name='schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='schedule_builder.Schedule'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='courses',
            field=models.ManyToManyField(related_name='students', through='schedule_builder.Enrollment', to='schedule_builder.Course'),
        ),
    ]
