# Generated by Django 3.0.8 on 2020-08-25 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_builder', '0013_projectedenrollment_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectedenrollment',
            name='year',
            field=models.IntegerField(default=2019, verbose_name='year'),
        ),
    ]
